### PR TITLE
Fix ESLint errors and update Readme

### LINKED ISSUE #36: Add programatic style guide enforcement
The current version of the website was developed in plain text editors without a linter or enforcement of a style guide. Future merge requests will be enforced more zealously and settling all arguments with a programmatic enforcer is the easiest path forward.

### PR DESCRIPTION
**Pull request by jt-mchorse**
Closes #36

### CODE REVIEW

File: site/gatsby-site/src/templates/cite.js [hunk 1]
```diff
@@ -183,68 +225,64 @@ export default class IncidentCite extends Component {
...
-      },
-      site: {
-        siteMetadata: { docsLocation, title },
-      },
+      // allMdx,
+      allMongodbAiidprodIncidents: { group },
     } = data;
 
-    const gitHub = require('../components/images/github.svg');
+    // const navItems = allMdx.edges
```
Comment (smcgregor) [inline site/gatsby-site/src/templates/cite.js:232]: What is going on here?

Comment (jt-mchorse) [reply site/gatsby-site/src/templates/cite.js:232]: This var has never been used, I kept it for now to have your confirmation on removal.

Comment (smcgregor) [reply site/gatsby-site/src/templates/cite.js:232]: Ok, if it was never read go ahead and remove it. Is this the case in some of the other linted files?

Comment (jt-mchorse) [reply site/gatsby-site/src/templates/cite.js:232]: Yes

Comment (jt-mchorse) [reply site/gatsby-site/src/templates/cite.js]: Removed.

File: site/gatsby-site/pages/apps/submit.js [hunk 2]
```diff
@@ -96,214 +98,240 @@ const dateRegExp = /^(\+?\d{4})?\s?-?\s?(\(?\d{2}\)?)\s?-?\s?(\(?\d{2}\)?)\s?-?\
...
+    console.log('---------------------------');
+  };
 
   handleOnError = (err, file, inputElem, reason) => {
-    console.log(err)
-  }
+    console.log(err, file, inputElem, reason);
+  };
 
-  updateRelated = (incident_id) => {
```
Comment (smcgregor) [inline site/gatsby-site/pages/apps/submit.js:274]: parens were added in another case above. Are parens needed or not needed per the style guide?

Comment (jt-mchorse) [reply site/gatsby-site/pages/apps/submit.js:274]: https://prettier.io/docs/en/options.html#arrow-function-parentheses

We did not overwritten any rules, so it must be using always.

Comment (smcgregor) [reply site/gatsby-site/pages/apps/submit.js:274]: Why this change then? Should it not have parens around `incident_id`?

Comment (smcgregor) [reply site/gatsby-site/pages/apps/submit.js:274]: This is my only lingering doubt about this merge request, but I think I am good with landing this as soon as we close out this discussion.

Comment (jt-mchorse) [reply site/gatsby-site/pages/apps/submit.js:274]: It's our prettier version, "prettier": "^1.19.1", which is using "avoid" as default. shall we upgrade package version to latest?

Comment (smcgregor) [reply site/gatsby-site/pages/apps/submit.js:274]: We might as well be at the latest since changing this again at a later time will be annoying. Regardless, I don't feel strongly about it so long as we are consistent. Would you like to proceed as-is?

Comment (jt-mchorse) [reply site/gatsby-site/pages/apps/submit.js:274]: I've updated the package versions and fixed all lint issues.
